# Generated by Django 3.1.7 on 2021-04-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_count_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count_likes',
        ),
    ]
